### ISSUE TITLE
Week 01 作業回饋

### ISSUE THREAD

**Issue by azole** [Tonyrj3268/git-practice#1]
關於「說明 blob, tree, commit, branch, head 分別是什麼」，以 blob 為例，你完全照抄 https://docs.github.com/en/rest/git/blobs?apiVersion=2022-11-28 這一頁的內容？

**Comment by Tonyrj3268** [comment]
@azole 
是的，第一週我以為是要這種標準答案，經過上週上課後，這次有改變寫作業的方法了，至於第一週的作業我覺得已經過繳交期限我不宜再做更改了，所以我保持了原樣。

**Comment by azole** [comment]
為數不少的同學都有回頭調整第一週的作業成果，這件事不一定要做，不過，既然這個 repo 是 public 的，有空可以回頭調整，或是學期結束後改成 private or 刪除，天曉得哪次面試的時候，面試官摸過來看你的 github?

> 第一週的作業我覺得已經過繳交期限我不宜再做更改了，所以我保持了原樣。

未來工作上，類似這樣的事情，其實可以主動確認看看，特別是剛加入一個團隊，跟主管、mentor 還不熟的時候，不要自己猜，透過確認來磨合彼此的工作習慣。

week 02 作業確實進步很多，如果沒有其他要再跟我討論的事，這個 issue 可以 close 了。
