### ISSUE TITLE
Week 02 回饋

### ISSUE THREAD

**Issue by azole** [Tonyrj3268/git-practice#2]
## readme
有觀察到版本號會包含很多小版本，很好。

## sum
作業要求是以 array 函式來完成 sum，你選擇用 reduce，而不是其他 array 函式，為什麼？有研究過其他 array 函式嗎？為什麼不是選其他的？

## Fib 
你提供了兩種作法，本質上都是遞回，但第二種有用到 closure，請你分析一下第二種作法跟第一種作法的差異，有什麼優缺點？

## Stack
- stack 實作 ok，coding style 也合格
- 測試案例也合格

Stack 這題做得很好，那我進一步想要跟你討論一下，有沒有可能讓 print 也能被測試（被 assert）？

**Comment by Tonyrj3268** [comment]
>作業要求是以 array 函式來完成 sum，你選擇用 reduce，而不是其他 array 函式，為什麼？有研究過其他 array 函式嗎？為什麼不是選其他的？

- 我是從[MDN](https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce)這裡尋找 array 的實體方法，並且找到了`reduce`這個方法，覺得這個方式比較特別，且他的範例也是 array 元素加總，所以我選擇使用`reduce`。
- 課堂上有人示範了`map`, `forEach`函式也可以達成，我將補充進`sum.js`裡。
- 個人覺得`forEach`的做法比較直觀。

>你提供了兩種作法，本質上都是遞回，但第二種有用到 closure，請你分析一下第二種作法跟第一種作法的差異，有什麼優缺點？

- 在第二種方法中，我多建立了一個 dict 來存放遞回的結果，可以避免重複計算，這樣的優點是可以節省計算時間，但缺點是會佔用更多的記憶體。
- 另外閉包讓我可以建立一些變數在該 function 的作用域中，而不需要額外建立一個類別或是設置全域變數來存放變數。

>有沒有可能讓 print 也能被測試（被 assert）？

- 網路上有兩大做法
  1. 重寫 `console.log`來捕獲輸出並儲存進行測試。（補充進main.js）
  2. 使用`Jest`或是`Mocha`等測試框架，本質上也是替換了`console.log`來進行監視。

```javascript
const logSpy = jest.spyOn(console, "log"); // 監視 console.log

console.log("5, 8"); // 調用 console.log

expect(logSpy).toHaveBeenCalled(); // 驗證 console.log 是否被調用
expect(logSpy).toHaveBeenCalledWith("5, 8"); // 驗證調用時的參數

logSpy.mockRestore(); // 恢復原始的 console.log
```
